### ISSUE TITLE
Add synonymic 'check-deps' key to 'verify' key

### ISSUE THREAD

**Issue by MikhailKasimov** [openSUSE/zypper#101]
Hello!

Subj. 

A couple of days ago, I tried to refresh in mind what zypper key is responsible for dependencies checking. The first idea was ```zypper check-deps```, similary to ```--clean-deps``` option in ```zypper rm``` command. But the right way was ```verify``` key. So, the idea is to add ```check-deps``` key as a synonym to ```verify``` key, because ```check-deps``` seems to be more intuitive.

Thank you!

**Comment by mlandres** [comment]
Well, `verify` is what other packagemanagers like `rpm` use as well. Rather than hardcoding alternate names, I'd prefer to add general support for user defined aliases.

In the mean time you can use the subcommand feature. I.e. create a bash script named `zypper-check-deps` and put it somewhere in your PATH (e.g. `/usr/local/bin/zypper-check-deps `). Content:
```
#! /bin/bash
exec zypper verify "$@"
```
You can use it as a zypper command: `zypper check-deps --dry-run'
