### ISSUE TITLE
"zypper se --requires" need some improvements

### ISSUE THREAD

**Issue by trmdi** [openSUSE/zypper#192]
For example, this command shows that only 1 package requires libupnp6:
```
▶ sudo zypper se --requires libupnp6
i+ | libupnp-devel | Portable Universal Plug and Play (UPnP) SDK | package
```

But in fact, there are some other packages requires `libupnp6`

```
▶ sudo zypper rm libupnp6
The following 8 packages are going to be REMOVED:
  libupnp6 libupnp-devel mpd vlc vlc-codec-gstreamer vlc-codecs vlc-noX vlc-qt
```

**Comment by bzeller** [comment]
Thats because those packages do not directly depend on libupnp6 , or they use a different provide to query the package.

If you check what libupnp6 provides you get those amonst others:
zypper info --provides libupnp6
<snip/>                  
    libupnp.so.6()(64bit)
    libupnp6 = 1.6.25-lp150.1.1
    libupnp6(x86-64) = 1.6.25-lp150.1.1

A package can now depend on one of those and get the libupnp6 package, for example vlc-noX depends on libupnp.so.6()(64bit) and not on libupnp6, which would not be found by your query.

If you instead search for libupnp.so.6 you will find more packages.

**Comment by bzeller** [comment]
We could improve the situation by providing special switches to zypper search e.g.:
zypper search --requires-package libupnp6  which then would internally create a query looking for provides of that package. I will leave the bug open as a feature request.

**Comment by awerlang** [comment]
Seems it was implemented as `--requires-pkg`.

**Comment by trmdi** [comment]
> Seems it was implemented as `--requires-pkg`.

Yeah, could we close this now?
