### ISSUE TITLE
bogus cs translation

### ISSUE THREAD

**Issue by jirislaby** [openSUSE/zypper#283]
https://github.com/openSUSE/zypper/blob/2a0c23af1cb050c1f72b7e84887794aa57fb8436/po/cs.po#L2105

The above does not make much sense. I don't know how to translate dangling symlink. Definitely not by `klátí se`, though.

The sentence below (line 2106) is not 100% correct too.

**Comment by jreidinger** [comment]
probably old translation as in weblate it is correctly translated. see https://l10n.opensuse.org/translate/zypper/master/cs/?checksum=&offset=&q=dangling&search=ftx&source=on&target=on&type=all&ignored=False&date=&only_user=&exclude_user=

**Comment by mlandres** [comment]
Probably because [Martin](https://l10n.opensuse.org/translate/zypper/master/cs/?checksum=&offset=&q=dangling&search=ftx&source=on&target=on&type=all&ignored=False&date=&only_user=&exclude_user=#history) fixed it in weblate ~an hour ago . It needs a bit of time until weblate pushes it to our repo (and we submitt the next zypper version).

**Comment by jirislaby** [comment]
> The sentence below (line 2106) is not 100% correct too.

Still wrong.

> The link must point to your core products .prod file in /etc/products.d.

does not translate to

> Tento symlink musí odkazovat na vaše hlavní produkty, .prod soubor v /etc/products.d.

The symlink, for sure, should not point to my main products.

**Comment by mlandres** [comment]
@mvidner thanks having fixed the [1st line](https://l10n.opensuse.org/translate/zypper/master/cs/?checksum=&offset=&q=dangling&search=ftx&source=on&target=on&type=all&ignored=False&date=&only_user=&exclude_user=). Do you mind helping us with the 2nd one?
