### ISSUE TITLE
[ Question ] download package and dependencies recursively

### ISSUE THREAD

**Issue by jehutyy** [openSUSE/zypper#344]
Hello, 
I'm trying to figure out wether `zypper` has a way to download package with dependency recursively as `yumdownloader` 
or `apt install --download-only` ?

I searched through man page but it appears zypper only has `download` options which just download rpm for the queried package.

It would be very useful for airgap installation for instance.

If not, is there any chances that this feature is being developped at the moment ?

**Comment by mlandres** [comment]
`# zypper --disable-system-resolvables in --download-only zypper`
`disable-system-resolvables` behaves as if it is an empty system. It will download zypper and all it's dependencies. Without the option it will just download  the packages not yet installed.

`# zypper --pkg-cache-dir /tmp/CACHE --disable-system-resolvables in --download-only zypper`
To use an alternate package cache rather than `/var/cache/zypp/packages`.
