### ISSUE TITLE
zypper applies deltarpm in download-only mode by default

### ISSUE THREAD

**Issue by rhabacker** [openSUSE/zypper#581]
If zypper is used with --releasever to download packages for a later system update e.g. on a Leap 15.5 system by calling 

zypper --releasever=15.6 ref
zypper --releasever=15.6 update -d

a partial update of deltarpm packages is already performed, although only the download option has been selected. See the following example:

```
...
Retrieve: glibc-locale-base-2.38-150600.14.17.2.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (499/1942), 1.4 MiB    
Retrieve delta: ./x86_64/glibc-locale-base-2.31_2.38-150300.89.2_150600.14.17.2.x86_64.drpm, 440.4 KiB
retrieve: glibc-locale-base-2.31_2.38-150300.89.2_150600.14.17.2.x86_64.drpm ...
Apply delta: ./glibc-locale-base-2.31_2.38-150300.89.2_150600.14.17.2.x86_64.drpm ...
``` 
This is unfavourable, as it may cause the system to become unstable.

In the configuration file for zypper there is the option `download.use_deltarpm=false` with which the basic use of deltarpm packages can be switched off.  However, this is only a poor workaround, as you also want to download deltarpm packages with the -d option, but do not want to use them immediately, as described above.

**Comment by mlandres** [comment]
@rhabacker a delta is **not** applied to the system.
The `applydeltarpm` command combines data of the installed package and the downloaded delta rpm to create the full rpm locally. This is part of the download workflow and does not change the system content. Only installing the full rpm does.

**Comment by rhabacker** [comment]
@mlandres: Thanks for the quick feedback

The message ‘Applying delta ...’ is unfortunately not very clear and could just as well refer to the installed package, which led to the misinterpretation.   

I.e. the delta rpm is downloaded and applied to an installed package, creating a new temporary package.
According to https://github.com/openSUSE/libzypp/blob/4719e55cdffaff4c9ccf2208f7fe3ebe8739bbd6/zypp.conf#L215
this is an expensive operation, from which I conclude that it slows down the download process.  Since bandwidth is no longer an issue these days, would it make sense to set the setting for download.use_deltarpm to false by default ?

**Comment by mlandres** [comment]
It may depend on where in the world you are located at. The option was introduced in 2007, so CPU and memory may not be such a big issue either. But yes, it trades CPU against bandwidth. That's why the build system and d.o.o. AFAIK do not offer deltas for every package. They've got heuristics telling whether it's worth offering a delta at all. It's basically up to the distribution to decide how they ship the package. So we're reluctant to change the default.

```
# zgrep filename /var/cache/zypp/raw/opensSUSE:update-oss/repodata/*-deltainfo.xml.gz | grep x86_64| wc -l
75
```
My openSUSE-15.4 e.g. offers just 75 deltas at all - and is almost at the end of it's lifetime.  The SLES repos however seem to be more generous. But without numbers it's hard to tell how good the build service's heuristics are.
